language: node_js
node_js:
  - "12"
services:
  - docker
branches:
  only:
    - master

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker build -t "jklolita"/pea3nut-info:latest .
  - docker image build ./ -t dist
  - docker container create -p 32769:80 dist
